// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PostgresWebAPI.Data;

#nullable disable

namespace PostgresWebAPI.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20240613204356_LoginCredsMigration")]
    partial class LoginCredsMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PostgresWebAPI.Data.ConstructionProjectEntity", b =>
                {
                    b.Property<int>("projectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("projectId"));

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("endDate")
                        .HasColumnType("text");

                    b.Property<string>("projectName")
                        .HasColumnType("text");

                    b.Property<string>("startDate")
                        .HasColumnType("text");

                    b.HasKey("projectId");

                    b.ToTable("ConstructionProjects");
                });

            modelBuilder.Entity("PostgresWebAPI.Data.LoginCredentialsEntity", b =>
                {
                    b.Property<string>("userName")
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .HasColumnType("text");

                    b.HasKey("userName");

                    b.ToTable("LoginCredentials");
                });
#pragma warning restore 612, 618
        }
    }
}
